# Generated by Django 2.2.2 on 2021-02-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210207_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='game',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
