# Generated by Django 2.2.2 on 2021-02-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherinfo_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='staff_number',
            field=models.CharField(max_length=8),
        ),
    ]
